---
- name: restart
  hosts: all
  tasks:
    # - name: Rebooting the cloud server
    # reboot:
    - name: logout
      shell: |
        pkill -KILL -u $USER
    - name: check microk8s
      shell: |
        microk8s.kubectl --version
      register: result_var
    - name: print
      debug:
        var: result_var


