---
- name: run pods
  hosts: all
  vars:
    podfile: "/home/jhasomak/simple-pod.yml"
  become: true
  tasks:
  - name: get curr directory
    shell: pwd
    register: result
  - name: print
    debug:
      var: result
  - name: create a pod
    shell: |
      microk8s kubectl apply -f simple-pod.yml
